spring.application.name=ms-order
server.port=8080

# Database Configuration
spring.datasource.url=jdbc:postgresql://localhost:5433/order_db
spring.datasource.username=paymentuser
spring.datasource.password=paymentpass
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA / Hibernate
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# Flyway
spring.flyway.enabled=true
spring.flyway.locations=classpath:db/migrations

# AWS Configuration (LocalStack)
spring.cloud.aws.region.static=us-east-1
spring.cloud.aws.credentials.access-key=test
spring.cloud.aws.credentials.secret-key=test
spring.cloud.aws.endpoint=http://localhost:4566

# SNS Configuration
aws.sns.topic.order-events=arn:aws:sns:us-east-1:000000000000:order-events-topic