version: '3.8'

services:
  api:
    build: .
    container_name: ms-order-api
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/order_db
      SPRING_DATA_REDIS_HOST: redis
      SPRING_CLOUD_AWS_ENDPOINT_OVERRIDE: http://localstack:4566
      SPRING_CLOUD_AWS_SQS_ENDPOINT: http://localstack:4566
      SPRING_CLOUD_AWS_SNS_ENDPOINT: http://localstack:4566 # Configuração específica para o SNS
      SPRING_CLOUD_AWS_CREDENTIALS_PROVIDER: anonymous
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_started
      localstack:
        condition: service_started
    networks:
      - ecommerce-network

  db:
    image: postgres:16
    container_name: postgres-db
    environment:
      POSTGRES_USER: paymentuser
      POSTGRES_PASSWORD: paymentpass
    ports:
      - "5433:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./init-db.sql:/docker-entrypoint-initdb.d/init.sql
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U paymentuser"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - ecommerce-network

  redis:
    image: redis:7-alpine
    container_name: redis-cache
    ports:
      - "6379:6379"
    networks:
      - ecommerce-network

  localstack:
    image: localstack/localstack:3.0
    container_name: ms-order-localstack
    ports:
      - "4566:4566"            # LocalStack Gateway
      - "4510-4559:4510-4559"  # external services port range
    environment:
      - SERVICES=sns,sqs
      - DEBUG=1
      - DOCKER_HOST=unix:///var/run/docker.sock
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
    networks:
      - ecommerce-network

volumes:
  pgdata:

networks:
  ecommerce-network:
    driver: bridge