version: '3.8'

services:
  db:
    image: postgres:16
    container_name: postgres-db
    environment:
      POSTGRES_USER: paymentuser
      POSTGRES_PASSWORD: paymentpass
    ports:
      - "5433:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./init-db.sql:/docker-entrypoint-initdb.d/init.sql
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U paymentuser"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - ecommerce-network

  localstack:
    image: localstack/localstack:3.0
    container_name: ms-order-localstack
    ports:
      - "4566:4566"            # LocalStack Gateway
      - "4510-4559:4510-4559"  # external services port range
    environment:
      - SERVICES=sns,sqs
      - DEBUG=1
      - DOCKER_HOST=unix:///var/run/docker.sock
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
    networks:
      - ecommerce-network

volumes:
  pgdata:

networks:
  ecommerce-network:
    driver: bridge
