version: '3.8'

services:
  api:
    build: .
    container_name: ms-order-api
    ports:
      - "8080:8080"
    environment:
      # --- Banco de Dados ---
      SPRING_DATASOURCE_URL: jdbc:postgresql://${DB_HOST}:${DB_PORT}/${DB_NAME}
      SPRING_DATASOURCE_USERNAME: ${DB_USER}
      SPRING_DATASOURCE_PASSWORD: ${DB_PASSWORD}

      # --- Redis ---
      SPRING_DATA_REDIS_HOST: ${REDIS_HOST}
      SPRING_DATA_REDIS_PORT: ${REDIS_PORT}

      # --- AWS / LocalStack ---
      SPRING_CLOUD_AWS_ENDPOINT_OVERRIDE: http://${LOCALSTACK_HOST}:${LOCALSTACK_PORT}
      SPRING_CLOUD_AWS_SQS_ENDPOINT: http://${LOCALSTACK_HOST}:${LOCALSTACK_PORT}
      SPRING_CLOUD_AWS_SNS_ENDPOINT: http://${LOCALSTACK_HOST}:${LOCALSTACK_PORT}
      SPRING_CLOUD_AWS_CREDENTIALS_PROVIDER: anonymous
      AWS_SNS_TOPIC_ORDER-EVENTS: ${ORDER_EVENTS_TOPIC_ARN}
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_started
      localstack:
        condition: service_started
    networks:
      - ecommerce-network

  db:
    image: postgres:16
    container_name: postgres-db
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    ports:
      - "5433:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./init-db.sql:/docker-entrypoint-initdb.d/init.sql
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DB_USER}"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - ecommerce-network

  redis:
    image: redis:7-alpine
    container_name: redis-cache
    ports:
      - "6379:6379"
    networks:
      - ecommerce-network

  localstack:
    image: localstack/localstack:3.0
    container_name: ms-order-localstack
    ports:
      - "${LOCALSTACK_PORT}:${LOCALSTACK_PORT}" # Expõe a porta do LocalStack
      - "4510-4559:4510-4559"
    environment:
      - SERVICES=sns,sqs
      - DEBUG=1
      - DOCKER_HOST=unix:///var/run/docker.sock
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
    networks:
      - ecommerce-network

volumes:
  pgdata:

networks:
  ecommerce-network:
    driver: bridge